version: "2"
services:
    pycones2016:
        image: pycones2016:1.0
        container_name: pycones2016
        env_file: .env
        command: bash -c "/venv/bin/python manage.py migrate && /venv/bin/python manage.py collectstatic --noinput && /venv/bin/python manage.py compilemessages && /venv/bin/gunicorn -w 6 -t 60 -b unix:/pycones2016-sock/pycones2016.sock pycones.wsgi --access-logfile gunicorn-access-log --error-logfile gunicorn-error-log --log-level debug"
        volumes:
            - /home/yami/pycones2016:/pycones2016-sock
            - /home/yami/pycones2016/pycones/assets:/pycones2016/pycones/assets
            - /home/yami/pycones2016/pycones/media:/pycones2016/pycones/media
        network_mode: host

